# Generated by Django 5.2.7 on 2025-11-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_cliente_puntos_acumulados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='puntos_acumulados',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Puntos_Acumulados'),
        ),
    ]
